### ISSUE TITLE
fdroid rfp

### ISSUE THREAD

**Issue by yashpalgoyal1304** [tfg13/LanXchange#16]
hi, would u support ur app being included in fdroid store?

https://f-droid.org

**Comment by yashpalgoyal1304** [comment]
ohh, rfp means request for package.

this issue's rfp issue in fdroid repo: https://gitlab.com/fdroid/rfp/-/issues/1728

**Comment by tfg13** [comment]
Sure, go for it.

Note I have not touched this at all in >3 years. I did find some time recently and would like to do a maintenance update in the future, but no promises :)

**Comment by yashpalgoyal1304** [comment]
thanks for "supporting the inclusion"

ohkay, thanks for the status info. Just one one-time task will need ur
efforts : the directory syntax or the file-folder structure so that fdroid
can automatically pick up the info, things like
- fastlane xor Triple - T
- use of release tags
- screenshot folder (optional)
- changelog folder (optional)

i dont know if ur repo already has those things or not, someone from fdroid
team will mention about this on fdroid/rfp issue i mentioned above - that
can be viewed w/o logging in too (if u dont have gl account). Also, my
bird's eye observation says that it is not that much work if u're familiar
with it.

**Comment by jugendhacker** [comment]
I'm trying to get this building, got the following problem:
```
> Task :android:processReleaseMainManifest FAILED
/tmp/LanXchange/modules/android/AndroidManifest.xml:7:5-9:44 Error:
        uses-sdk:minSdkVersion 1 cannot be smaller than version 9 declared in library [com.android.support:design:25.2.0] /home/julian/.gradle/caches/transforms
-2/files-2.1/813bc61ae7065e99e25aa712abd7bb32/design-25.2.0/AndroidManifest.xml as the library might be using APIs not available in 1
        Suggestion: use a compatible library with a minSdk of at most 1,
                or increase this project's minSdk version to at least 9,
                or use tools:overrideLibrary="android.support.design" to force usage (may lead to runtime failures)

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
```

**Comment by tfg13** [comment]
> I'm trying to get this building, got the following problem:

Yeah sorry about that. To be honest, I am not surprised this doesn't build, the android version is ~4? years old. And I can't promise how fast I will get to fix things. I remember trying to fix all the build problems like a year ago and got so frustrated with gradle I gave up.

I have, however, partially fixed the build for the PC version recently, android is on the list as well. Bot no promises, as both gradle and android can be a bit messy to update.

Speaking of: Even if it compiles, I need to update a bunch of things in the app. This is not really a problem for f-droid, but the target SDK versions are so low google won't even accept app updates right now. And of course updating the SDK version means the rules around file access have changed yet again and I need to do a bunch of changes there as well. Oh and power saving, it it getting harder and harder to run a background service. Can you tell I am not looking forward to doing this? :D

**Comment by jugendhacker** [comment]
Okay so I think F-Droid should wait with packaging your app until you adopted to the recent SDK level changes and fixed you build.
