### ISSUE TITLE
LanXchange stopped working with Java 8 update 351 on Windows

### ISSUE THREAD

**Issue by josiasmat** [tfg13/LanXchange#20]
LanXchange stopped working with Java 8 update 351 on Windows. It opens and doesn't show any error messages, but it doesn't show files shared by other devices, nor files shared by it show in other devices.

Downgrading Java to update 341 solves the problem.

**Comment by tfg13** [comment]
Hmm the changelog for 351 looks quite short and innocent: https://www.oracle.com/java/technologies/javase/8u351-relnotes.html

Can you please attach the logs (in the main directory).

Note I haven't patched this in years, no promises I still can find the time to do it :(
